// Subject
export const CREATE_SUBJECT = "CREATE_SUBJECT";
export const READ_SUBJECT = "READ_SUBJECT";
export const READ_SUBJECT_FAILED = "READ_SUBJECT_FAILED";
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const GET_SUBJECT = "GET_SUBJECT";

// Question & Answer
export const CREATE_INITIAL_QUESTIONS = "CREATE_INITIAL_QUESTIONS";
export const READ_QUESTION_ANSWERS = "READ_QUESTION_ANSWERS";
export const UPDATE_QUESTION_ANSWERS = "UPDATE_QUESTION_ANSWERS";

// UI State
export const SHOW_BACKDROP = "SHOW_BACKDROP";
export const HIDE_BACKDROP = "HIDE_BACKDROP";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";

// Auth
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

// General
export const API_FAILED = "API_FAILED";
